export const electronicComponents = [
  {
    type: "Sensors",
    components: [
      { name: "Light Sensor", unit: ["Lux"], min: "", max: "" },
      { name: "Gas Sensor", unit: ["PPM"], min: "", max: "" },
      {
        name: "Temperature Sensor",
        unit: ["Celsius", "Fahrenheit"],
        min: "",
        max: "",
      },
      { name: "Humidity Sensor", unit: ["Percentage"], min: "", max: "" },
      { name: "Pressure Sensor", unit: ["Bar", "Pascal"], min: "", max: "" },
      { name: "Motion Sensor", unit: ["Distance"], min: "", max: "" },
      { name: "Proximity Sensor", unit: ["cm", "inches"], min: "", max: "" },
      { name: "CO2 Sensor", unit: ["PPM"], min: "", max: "" },
      { name: "Ultrasonic Sensor", unit: ["cm"], min: "", max: "" },
      { name: "Smoke Sensor", unit: ["PPM"], min: "", max: "" },
      { name: "Infrared Sensor", unit: ["Distance"], min: "", max: "" },
      { name: "Accelerometer", unit: ["m/s²"], min: "", max: "" },
      { name: "Gyroscope", unit: ["Degree/Second"], min: "", max: "" },
      { name: "Flame Sensor", unit: ["PPM"], min: "", max: "" },
      { name: "LIDAR", unit: ["Meters"], min: "", max: "" },
      { name: "Radar Sensor", unit: ["GHz"], min: "", max: "" },
      { name: "Thermal Camera", unit: ["Celsius"], min: "", max: "" },
      { name: "VOC Sensor", unit: ["PPM"], min: "", max: "" },
    ],
  },
  {
    type: "Actuators",
    components: [
      { name: "Motor", unit: ["RPM", "Watts"], min: "", max: "" },
      { name: "Servo", unit: ["RPM", "Watts"], min: "", max: "" },
      { name: "Pump", unit: ["RPM", "Watts"], min: "", max: "" },
      { name: "Fan", unit: ["RPM", "Watts"], min: "", max: "" },
      { name: "Heater", unit: ["Watts"], min: "", max: "" },
      { name: "Linear Actuator", unit: ["mm", "cm"], min: "", max: "" },
      { name: "Solenoid Valve", unit: ["Volts"], min: "", max: "" },
      { name: "Electric Valve", unit: ["Volts"], min: "", max: "" },
      { name: "Shutter Actuator", unit: ["RPM"], min: "", max: "" },
      { name: "LED", unit: ["Lumens"], min: "", max: "" },
      { name: "Vibration Motor", unit: ["RPM"], min: "", max: "" },
      { name: "Stepper Motor", unit: ["RPM", "Watts"], min: "", max: "" },
      { name: "Piezoelectric Actuator", unit: ["Volts"], min: "", max: "" },
    ],
  },
  {
    type: "Switches",
    components: [
      { name: "Relay Switch", unit: ["boolean"], state: true },
      { name: "Button Switch", unit: ["boolean"], state: true },
      { name: "Toggle Switch", unit: ["boolean"], state: true },
      { name: "Push Button", unit: ["boolean"], state: true },
      { name: "Light Switch", unit: ["boolean"], state: true },
      { name: "Rotary Switch", unit: ["boolean"], state: true },
      { name: "PIR Sensor Switch", unit: ["boolean"], state: true },
      { name: "Magnetic Switch", unit: ["boolean"], state: true },
      { name: "Foot Switch", unit: ["boolean"], state: true },
    ],
  },
  {
    type: "Controllers",
    components: [
      { name: "Microcontroller", unit: ["MHz", "Volts"], min: "", max: "" },
      { name: "Raspberry Pi", unit: ["GHz", "Volts"], min: "", max: "" },
      { name: "Arduino", unit: ["MHz", "Volts"], min: "", max: "" },
      { name: "ESP8266", unit: ["MHz", "Volts"], min: "", max: "" },
      { name: "ESP32", unit: ["MHz", "Volts"], min: "", max: "" },
      { name: "BeagleBone", unit: ["GHz", "Volts"], min: "", max: "" },
      { name: "NodeMCU", unit: ["MHz", "Volts"], min: "", max: "" },
      { name: "Intel Edison", unit: ["GHz", "Volts"], min: "", max: "" },
      { name: "STM32", unit: ["MHz", "Volts"], min: "", max: "" },
    ],
  },
  {
    type: "Displays",
    components: [
      { name: "LED Display", unit: ["Lumens"], min: "", max: "" },
      { name: "LCD Display", unit: ["Lumens"], min: "", max: "" },
      { name: "OLED Display", unit: ["Lumens"], min: "", max: "" },
      { name: "TFT Display", unit: ["Lumens"], min: "", max: "" },
      { name: "E-Paper Display", unit: ["Lumens"], min: "", max: "" },
      { name: "VFD Display", unit: ["Lumens"], min: "", max: "" },
    ],
  },
  {
    type: "Power Management",
    components: [
      { name: "Battery", unit: ["mAh"], min: "", max: "" },
      { name: "Power Supply", unit: ["Volts", "Amps"], min: "", max: "" },
      { name: "Voltage Regulator", unit: ["Volts"], min: "", max: "" },
      { name: "DC-DC Converter", unit: ["Volts", "Amps"], min: "", max: "" },
      { name: "Solar Panel", unit: ["Watts"], min: "", max: "" },
      { name: "UPS", unit: ["Watts"], min: "", max: "" },
      { name: "Energy Harvesting Module", unit: ["Volts"], min: "", max: "" },
      { name: "Inductive Charging", unit: ["Watts"], min: "", max: "" },
    ],
  },
  {
    type: "Communication Modules",
    components: [
      { name: "Wi-Fi Module", unit: ["Mbps"], min: "", max: "" },
      { name: "Bluetooth Module", unit: ["Mbps"], min: "", max: "" },
      { name: "ZigBee Module", unit: ["Mbps"], min: "", max: "" },
      { name: "LoRa Module", unit: ["Kbps"], min: "", max: "" },
      { name: "NFC Module", unit: ["MHz"], min: "", max: "" },
      { name: "RF Module", unit: ["MHz"], min: "", max: "" },
      { name: "5G Module", unit: ["Gbps"], min: "", max: "" },
      { name: "Wi-Fi 6 Module", unit: ["Gbps"], min: "", max: "" },
    ],
  },
  {
    type: "Sensors (Advanced)",
    components: [
      { name: "LIDAR", unit: ["Meters"], min: "", max: "" },
      { name: "Radar Sensor", unit: ["GHz"], min: "", max: "" },
      { name: "Thermal Camera", unit: ["Celsius"], min: "", max: "" },
      { name: "Flame Sensor", unit: ["PPM"], min: "", max: "" },
      { name: "Distance Sensor", unit: ["cm"], min: "", max: "" },
      {
        name: "Environmental Sensor",
        unit: ["PPM", "Humidity", "Temperature"],
        min: "",
        max: "",
      },
      {
        name: "Air Quality Sensor",
        unit: ["PPM", "Micrograms"],
        min: "",
        max: "",
      },
    ],
  },
  {
    type: "Environmental Sensors",
    components: [
      { name: "Soil Moisture Sensor", unit: ["Percentage"], min: "", max: "" },
      { name: "Rain Sensor", unit: ["mm", "inches"], min: "", max: "" },
      { name: "UV Sensor", unit: ["UV Index"], min: "", max: "" },
      { name: "Wind Speed Sensor", unit: ["m/s", "km/h"], min: "", max: "" },
      { name: "Water Flow Sensor", unit: ["L/min"], min: "", max: "" },
    ],
  },
  {
    type: "Audio Components",
    components: [
      { name: "Microphone", unit: ["dB"], min: "", max: "" },
      { name: "Speaker", unit: ["Watts"], min: "", max: "" },
      { name: "Buzzer", unit: ["Watts"], min: "", max: "" },
    ],
  },
];
